### PR TITLE
[rate-limit-controller] Fix and improve typing, remove `any` usage

### LINKED ISSUE #3729: `rate-limit-controller`: Replace use of `any` with proper types (non-test files only)

### PR DESCRIPTION
**Pull request by MajorLift**
## Explanation

- Fix all `any` usage and more typing fixes and improvements.
- Define `RateLimitedApiMap`, `RateLimitedRequests` for readability and clarity.
- Rename types (this can be reverted if it's disruptive to any downstream package):
  - `GetRateLimitState` -> `RateLimitControllerGetStateAction`.
  - `RateLimitStateChange` -> `RateLimitControllerStateChangeEvent`.
  - `CallApi` -> `RateLimitControllerCallApiAction`.

## References

- Closes #3729 

### Added

- Add and export types `RateLimitedApiMap`, `RateLimitedRequests`. ([#3963](https://github.com/MetaMask/core/pull/3963))
  - `RateLimitedApiMap` represents the type of the `RateLimitedApis` generic parameter used throughout the controller.
  - `RateLimitedRequests` represents the type of the `request` property of `RateLimitState`.

### Changed

- **BREAKING:** Rename types to align with conventions followed by other controllers. ([#3963](https://github.com/MetaMask/core/pull/3963))
  - `GetRateLimitState` is now `RateLimitControllerGetStateAction`.
  - `RateLimitStateChange` is now `RateLimitControllerStateChangeEvent`.
  - `CallApi` is now `RateLimitControllerCallApiAction`.
- Add `@metamask/utils` `^8.3.0` as a dependency. ([#3963](https://github.com/MetaMask/core/pull/3963))

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by Mrtenz — DISMISSED** [review]

File: packages/rate-limit-controller/src/RateLimitController.ts [hunk 1]
```diff
@@ -122,11 +142,11 @@ export class RateLimitController<
     this.rateLimitCount = rateLimitCount;
 
     this.messagingSystem.registerActionHandler(
-      `${name}:call` as const,
+      `${name}:call`,
       (
         origin: string,
         type: keyof RateLimitedApis,
-        ...args: Parameters<RateLimitedApis[keyof RateLimitedApis]['method']>
+        ...args: Parameters<RateLimitedApis[typeof type]['method']>
```
Comment (MajorLift) [inline packages/rate-limit-controller/src/RateLimitController.ts:149]: `args` should represent the result of querying `RateLimitedApis` with the specific `type` passed in as the second argument, not all possible Api types stored in state. 

`keyof RateLimitedApis` is only the constraint for the `type` param, not its type.

File: packages/rate-limit-controller/src/RateLimitController.ts [hunk 2]
```diff
@@ -184,16 +204,19 @@ export class RateLimitController<
...
-
+      const previous =
+        (state as unknown as RateLimitState<RateLimitedApis>).requests[api][
+          origin
+        ] ?? 0;
       if (previous === 0) {
         setTimeout(() => this.resetRequestCount(api, origin), rateLimitTimeout);
       }
+      return Object.assign(state, {
+        requests: {
```
[the remark this answers is not in the document]
Comment (MajorLift) [reply packages/rate-limit-controller/src/RateLimitController.ts]: This is a great idea! Applied here: https://github.com/MetaMask/core/pull/3963/commits/b39365694937612fc3077eccf5f0f779c8a04ec2

File: packages/rate-limit-controller/src/RateLimitController.ts [hunk 3]
```diff
@@ -184,16 +204,19 @@ export class RateLimitController<
...
       if (previous === 0) {
         setTimeout(() => this.resetRequestCount(api, origin), rateLimitTimeout);
       }
+      return Object.assign({}, state, {
+        requests: {
+          ...(state.requests as RateLimitedRequests<RateLimitedApis>),
+          [api]: { [origin]: previous + 1 },
+        },
+      });
     });
```
Comment (mcmire) [inline packages/rate-limit-controller/src/RateLimitController.ts:220]: Do we need to be inside of the `update` to access the `state` to set `previous`? It seems like we can take away one of the type assertions here:

``` suggestion
    const previous = this.state.requests[api][origin] ?? 0;
    this.update((state) => {
      if (previous === 0) {
        setTimeout(() => this.resetRequestCount(api, origin), rateLimitTimeout);
      }
      return Object.assign({}, state, {
        requests: {
          ...(state.requests as RateLimitedRequests<RateLimitedApis>),
          [api]: { [origin]: previous + 1 },
        },
      });
    });
```

Comment (mcmire) [reply packages/rate-limit-controller/src/RateLimitController.ts:220]: Also, is the type on `origin` correct? I tried to change the `update` call so that we are directly modifying state (well, the draft state) instead of returning an object, but the type on `origin` seemed to be interfering for some reason.

**Review by mcmire — COMMENTED** [review]
Overall looks good, just had some minor comments.

**Comment by mcmire** [comment]
@MajorLift I'm assuming we want to wait until the parent PR is merged before merging this, correct?

File: packages/rate-limit-controller/src/RateLimitController.ts [hunk 4]
```diff
@@ -106,9 +124,11 @@ export class RateLimitController<
     implementations: RateLimitedApis;
   }) {
     const defaultState = {
-      requests: Object.keys(implementations).reduce(
+      requests: (
+        Object.keys(implementations) as (keyof RateLimitedApis)[]
```
[the remark this answers is not in the document]
Comment (MajorLift) [reply packages/rate-limit-controller/src/RateLimitController.ts]: Applied here! https://github.com/MetaMask/core/pull/3963/commits/ebec2ba94358ddaab162f7aac4cf6d89cf8e5bbd

File: packages/rate-limit-controller/src/RateLimitController.ts (hunk 3 above)
Comment (MajorLift) [reply packages/rate-limit-controller/src/RateLimitController.ts]: Setting `previous` outside of `update` applied here: https://github.com/MetaMask/core/pull/3963/commits/71cc83dfab8d6c3ef7ff99bdfbbdadef9a07e9e4

Mutating state in-place seems to work with `Object.assign`: https://github.com/MetaMask/core/pull/3963/commits/49e6e05da30ffc5d50b00dbdf68fee334b3b35b1

File: packages/rate-limit-controller/src/RateLimitController.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (MajorLift) [reply packages/rate-limit-controller/src/RateLimitController.ts]: Added `@metamask/utils` as dep: https://github.com/MetaMask/core/pull/3963/commits/66e78b8eec5b40c2bb4956cc20bafce471804715

**Review by Mrtenz — APPROVED** [review]

**Review by cryptodev-2s — APPROVED** [review]
LGTM!
