### PR TITLE
Fix `getRestricted` method: aligns runtime and type-level handling of omitted or empty inputs

### LINKED ISSUE #3648: [base-controller] `getRestricted` infers the wrong types when it has no allowed actions/events
When constructing a restricted controller messenger with no allowed actions, it will infer the "allowed action" type as encompassing all actions. This puts the types and runtime behavior out-of-sync; at runtime, no allowed actions means you can't call any external actions, but at the type level it acts as though you could call all of them.

Everything applies equally to events as well; the same problem is present for both actions and events.

For example:

```TypeScript
type MessageEvent = {
  type: 'MessageController:message';
  payload: [string];
};
type OtherEvent = {
  type: 'OtherController:other';
  payload: [unknown];
};

// Global messenger setup with two events: one for the MessengerController, and one external.
const controllerMessenger = new ControllerMessenger<
  never,
  MessageEvent | OtherEvent
>();
// No explicit type parameters given, they are inferred.
// Note that no allowed events are specified, so "OtherController:other" should be disallowed
const restrictedControllerMessenger = controllerMessenger.getRestricted({
  name: 'MessageController',
});

// This should result in a type error, but it does not. Instead it throws at runtime.
// "AllowedActions" has been inferred as being all actions
restrictedControllerMessenger.subscribe(
  'OtherController:other',
  () => undefined,
);
```

This is easily addressed by explicitly declaring the type parameter as `never` when constructing the `RestrictedMessengerController`. For example:

```TypeScript
// following from the same global ControllerMessenger as the above example

// Explicit type parameters given
const restrictedControllerMessenger = controllerMessenger.getRestricted<
  'MessageController',  // "name"
  never,                            // "allowedActions"
  never                            // "allowedEvents"
>({
  name: 'MessageController',
});

// This now correctly results in a type error
restrictedControllerMessenger.subscribe(
  'OtherController:other',
  () => undefined,
);
```

However, needing to explicitly declare type parameters for the empty case is not great. It's verbose, and makes this a bit more difficult to use.

We should investigate and find a way to ensure the inferred type is correct. If that's not possible, we should at least document this issue somewhere, so people are less likely to be caught off guard by it.

### PR DESCRIPTION
**Pull request by MajorLift**
## Motivation

Currently, if `getRestricted` generic params `Allowed{Actions,Events}` are omitted, the `allowed{Actions,Events}` function parameters are constrained with the full corresponding allowlists instead of `never`. This leads to inconsistencies between runtime and type-level behavior.

## Explanation

The `getRestricted` method of the `ControllerMessenger` class is updated:
1. If its `AllowedActions` or `AllowedEvents` generic parameters are omitted, a default argument of `never` is assigned, and `allowedActions`, `allowedEvents` are also constrained to empty arrays or `undefined`.
2. If its `allowedActions` or `allowedEvents` function arguments are non-empty arrays, union(s) of their corresponding type names are required to be passed into generic parameters `AllowedActions`, `AllowedEvents`. This can cause some duplication of allowlists between type-level generics and value-level function parameters. 

These changes align the type-level and runtime behavior of `getRestricted`, so that omitted or empty inputs consistently represent a set of empty allowlists. 

This change should not affect downstream JavaScript code, but may be disruptive to TypeScript code. 

## References

- Closes #3648

#### Changed

- **BREAKING:** The `getRestricted` method of the `ControllerMessenger` class has major API changes that may require updates to its existing instances in downstream code. These changes align the type-level and runtime behavior of `getRestricted`, so that omitted or empty inputs consistently represent a set of empty allowlists. ([$4013](https://github.com/MetaMask/core/pull/4013))
  - If the `AllowedActions`, `AllowedEvents` generic parameters are omitted, they are always assumed to be `never`.
    - Previously, omission of these generic parameters resulted in the full allowlists for the controller being inferred as type constraints for the `allowedActions`, `allowedEvents` function parameters.
  - If the `AllowedActions`, `AllowedEvents` generic parameters are both 
  - If the function parameters `allowedActions`, `allowedEvents` are a non-empty array, their corresponding type names must be explicitly passed into generic parameters `AllowedActions`, `AllowedEvents` to avoid type errors.
    - This may cause some duplication of allowlists between type-level and value-level code.
    - This requirement is only relevant for TypeScript code. A JavaScript consumer only needs to pass in the correct value-level function parameters. Because of this, these changes should not affect downstream JavaScript code, but may be disruptive to TypeScript code.
    - `getRestricted` is still able to flag `AllowedActions` and `AllowedEvents` members that should not be included in the allowlists, based on the `Action`, `Event` generic arguments passed into the `ControllerMessenger` instance.
- **BREAKING:** The `RestrictedControllerMessenger` class constructor now expects `allowedActions` and `allowedEvents` as required options.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by Mrtenz — DISMISSED** [review]

File: packages/base-controller/src/ControllerMessenger.ts [hunk 1]
```diff
@@ -430,12 +430,12 @@ export class ControllerMessenger<
...
     Namespace extends string,
-    AllowedAction extends NotNamespacedBy<Namespace, Action['type']>,
-    AllowedEvent extends NotNamespacedBy<Namespace, Event['type']>,
+    AllowedAction extends NotNamespacedBy<Namespace, Action['type']> = never,
+    AllowedEvent extends NotNamespacedBy<Namespace, Event['type']> = never,
   >({
     name,
-    allowedActions,
-    allowedEvents,
+    allowedActions = [],
```
Comment (Gudahtt) [inline packages/base-controller/src/ControllerMessenger.ts:437]: It looks like the drop in coverage is caused by this line. This makes the `?? null` branch in the `RestrictedControllerMessenger` unreachable.

Perhaps we could remove that branch, and change the `allowedActions` and `allowedEvents` parameters to be required in the `RestrictedControllerMessenger`  constructor? That would eliminate the unreachable branch and restore full coverage.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by Mrtenz — DISMISSED** [review]

**Review by Mrtenz — APPROVED** [review]
