### PR TITLE
chore: Fix suppressed lint errors in `@metamask/messenger`

### LINKED ISSUE #7371: Fix suppressed lint errors in `messenger`
Fix suppressed lint errors in this package.

### PR DESCRIPTION
**Pull request by Gudahtt**
## Explanation

All suppressed errors in the package have been fixed.

Fixes #7371

## References

N/A

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've communicated my changes to consumers by [updating changelogs for packages I've changed](https://github.com/MetaMask/core/tree/main/docs/contributing.md#updating-changelogs)
- [ ] I've introduced [breaking changes](https://github.com/MetaMask/core/tree/main/docs/breaking-changes.md) in this PR and have prepared draft pull requests for clients and consumer packages to resolve them

---

> [!NOTE]
> Adds explicit return types and minor typing adjustments to `Messenger` and its tests, and removes related ESLint suppressions.
> 
> - **@metamask/messenger**
>   - `packages/messenger/src/Messenger.ts`:
>     - Add explicit return types (`: void`, specific generics) to public and private methods (e.g., `registerActionHandler`, `unregisterActionHandler`, `clearActions`, `publish`, `unsubscribe`, `clearEventSubscriptions`, `clearSubscriptions`, delegation internals).
>     - Tighten delegate helpers’ types and return values; switch fallback usage to `??` in loops (`actions ?? []`, `events ?? []`).
>   - `packages/messenger/src/Messenger.test.ts`:
>     - Add explicit return types to class methods, handlers, and selectors; minor param rename (`s` → `input`).
> - **ESLint**
>   - `eslint-suppressions.json`: Remove entries for `packages/messenger/src/Messenger.ts` and `Messenger.test.ts` related to suppressed rules.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 6e27dd1a468d51103cb71d2078e49ae70b5d21b9. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/messenger/src/Messenger.ts [hunk 1]
```diff
@@ -765,14 +768,17 @@ export class Messenger<
     actions?: DelegatedActions;
     events?: DelegatedEvents;
     messenger: Delegatee;
-  }) {
-    for (const actionType of actions || []) {
+  }): void {
+    for (const actionType of actions ?? []) {
```
Comment (Mrtenz) [inline packages/messenger/src/Messenger.ts:772]: Maybe slightly cleaner to add a default value to `actions` and `events` here and in `revoke`?

```ts
function delegate({
  actions = [],
  events = [],
}) {
  // ...
}
```

Comment (Gudahtt) [reply packages/messenger/src/Messenger.ts:772]: Good suggestion, though I am not sure how to do that in a type safe way here, especially if we want to preserve the type inference of the type param based on the parameter value

Simply giving these parameters a `= []` initializer results in a type error, because `never[]` is not assignable to `DelegatedActions`
