### PR TITLE
[json-rpc-engine] Fix any types in catch blocks, refactor

### LINKED ISSUE #3720: `json-rpc-engine`: Replace use of `any` with proper types (non-test files only)
Look for the following string in non-test files to find these: ``// TODO: Replace `any` with type``

At time of writing, there were 6 instances.

### PR DESCRIPTION
**Pull request by MajorLift**
## Explanation

- Fixes all `any` usage in the `JsonRpcEngine` class.
- Errors are typed consistently as `unknown` to reflect actual usage in consumers and tests. - `JsonRpcEngineCallbackError` is no longer used within the package.

## References

- Closes #3720

### `@metamask/json-rpc-engine`

- **BREAKING:** The `error` types used in `JsonRpcEngineReturnHandler`, `JsonRpcEngineNextCallback`, and `JsonRpcEngineEndCallback` are widened from `JsonRpcEngineCallbackError` to `unknown`.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 1]
```diff
@@ -407,21 +428,36 @@ export class JsonRpcEngine extends SafeEventEmitter {
...
+   * Processes request object, and
+   * passes any error and response object to the given callback.
+   *
+   * Does not reject.
+   *
+   * @param callerReq - The request object from the caller.
+   * @param callback - The callback function.
+   * @returns Nothing.
+   */
+  async #handleRequest(
```
Comment (mcmire) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:456]: Is there another name we could come up with than `handleRequest`? It's my understanding that `handle` also handles the request, so it might be difficult to see at a glance how this is different.

Or, if we don't need to use this method anywhere else right now, perhaps we don't extract it yet?

File: packages/json-rpc-engine/src/createAsyncMiddleware.ts [hunk 2]
```diff
@@ -1,11 +1,15 @@
...
-  JsonRpcParams,
-  JsonRpcRequest,
-  PendingJsonRpcResponse,
+import {
+  type Json,
+  type JsonRpcParams,
+  type JsonRpcRequest,
+  type PendingJsonRpcResponse,
 } from '@metamask/utils';
+import { isNativeError } from 'util/types';
```
Comment (mcmire) [inline packages/json-rpc-engine/src/createAsyncMiddleware.ts:7]: Instead of using a "global" path can we use a relative one? I think this probably still works, but it's not a pattern we use and may end up being confusing. I think this is something that VSCode sometimes mistakenly does (although it may depend on your settings).

**Review by mcmire — COMMENTED** [review]
I left some minor comments but overall this looks good. Would be great to address these type issues as they seem to be multiplying, but that seems like another can of worms 😅

File: packages/json-rpc-engine/src/JsonRpcEngine.ts (hunk 1 above)
Comment (MajorLift) [reply packages/json-rpc-engine/src/JsonRpcEngine.ts]: Merging this back into `#handle` sounds like a good idea. Applied here: https://github.com/MetaMask/core/pull/3906/commits/8854416640c21867b5cbbbf35a22cbfaf5aeb21c.

The param type narrowing that I was trying to achieve with this refactor are accomplished further up in the file: https://github.com/MetaMask/core/pull/3906/files#diff-07a20aba14734ed38b0fbb7950cc14249fa7b9f836236734edef2001fb16359eR213-R243, mostly with type assertions.

File: packages/json-rpc-engine/src/createAsyncMiddleware.ts (hunk 2 above)
Comment (MajorLift) [reply packages/json-rpc-engine/src/createAsyncMiddleware.ts:7]: This is an import from the `node:util` module. Should we maybe avoid built-in node libraries?

Comment (mcmire) [reply packages/json-rpc-engine/src/createAsyncMiddleware.ts:7]: Oh, interesting. Wonder why it's using a subpath...

In any case, yes, I think we should try to make sure our libraries are as web-friendly as possible. I think Browserify does do some amount of polyfilling, but I'm not sure how extensive it is. So if there is a way to get around this, that would be preferable.

Comment (mcmire) [reply packages/json-rpc-engine/src/createAsyncMiddleware.ts:7]: Maybe `error instanceof Error` would suffice?

Comment (MajorLift) [reply packages/json-rpc-engine/src/createAsyncMiddleware.ts]: That works! https://github.com/MetaMask/core/pull/3906/commits/8d2a9d17e46152436d65a450e1852f9c0904417a

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 3]
```diff
@@ -239,24 +262,22 @@ export class JsonRpcEngine extends SafeEventEmitter {
...
         return next(async (handlerCallback) => {
           try {
             await JsonRpcEngine.#runReturnHandlers(returnHandlers);
-            // TODO: Replace `any` with type
-            // eslint-disable-next-line @typescript-eslint/no-explicit-any
-          } catch (error: any) {
-            return handlerCallback(error);
+          } catch (error) {
+            // TODO: Explicitly handle errors thrown from `#runReturnHandlers` that are not of type `JsonRpcEngineCallbackError`
+            return handlerCallback(error as JsonRpcEngineCallbackError);
```
Comment (mcmire) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:274]: Out of interest, do we need to change the type of the `error` argument? That seems to necessitate adding a type assertion here, so we'd now be lying about what the type of this error is. I just want to make sure: is this an intentional change, and do we think that this is preferable to using `any`?

Comment (MajorLift) [reply packages/json-rpc-engine/src/JsonRpcEngine.ts]: On second glance, the error is being thrown by `#runReturnHandlers`, which is guaranteed to throw `SerializableJsonRpcError | Error`. Removed the assertion and added a comment explaining why: https://github.com/MetaMask/core/pull/3906/commits/4b61631f0d1edb1cf2c4937bb8923459798c0084

**Comment by MajorLift** [comment]
I got rid of the TODOs and widened `JsonRpcEngineEndCallback`'s error param to `unknown`. 

This reflects its actual usage in the tests, where `end` takes in all error objects thrown by middleware regardless of their type.

https://github.com/MetaMask/core/pull/3906/commits/bac8e0edd2945bfd8d76ddebc40d1fd9e267c46a https://github.com/MetaMask/core/pull/3906/commits/b9549ed4806d47c04076969d8d87ea997d6d1730

File: packages/json-rpc-engine/src/JsonRpcEngine.ts (hunk 3 above)
Comment (MajorLift) [reply packages/json-rpc-engine/src/JsonRpcEngine.ts]: All of the other type assertions with TODOs are `end()` calls. 

With these, I think it doesn't make sense to inaccurately force `error` into the `JsonRpcEngineCallbackError` type when the test specs are passing in all error objects thrown by middleware into `end` callbacks regardless of their type. 

IMO whatever type safety gains we get from narrowing the error type from `unknown` are cancelled out by the fact that we have to use inaccurate type assertions everywhere to make the narrower type constraint work.

I widened `JsonRpcEngineCallback`'s `error` param to `unknown`, which lets us remove the TODO comments and the type assertions. What do you think? Would this be a regression in terms of type safety?
https://github.com/MetaMask/core/pull/3906/commits/bac8e0edd2945bfd8d76ddebc40d1fd9e267c46a https://github.com/MetaMask/core/pull/3906/commits/b9549ed4806d47c04076969d8d87ea997d6d1730

File: packages/json-rpc-engine/jest.config.js [hunk 4]
```diff
@@ -17,7 +17,7 @@ module.exports = merge(baseConfig, {
   // An object that configures minimum threshold enforcement for coverage results
   coverageThreshold: {
     global: {
-      branches: 100,
+      branches: 98.46,
```
Comment (mcmire) [inline packages/json-rpc-engine/jest.config.js:20]: It seems that there is an additional branch introduced in this PR that isn't covered by tests. Can you check?

File: packages/json-rpc-engine/src/JsonRpcEngine.ts (hunk 3 above)
Comment (mcmire) [reply packages/json-rpc-engine/src/JsonRpcEngine.ts]: I think these changes look better overall and make more sense than the previous changes.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 5]
```diff
@@ -239,23 +261,22 @@ export class JsonRpcEngine extends SafeEventEmitter {
...
         return next(async (handlerCallback) => {
           try {
             await JsonRpcEngine.#runReturnHandlers(returnHandlers);
-            // TODO: Replace `any` with type
-            // eslint-disable-next-line @typescript-eslint/no-explicit-any
-          } catch (error: any) {
-            return handlerCallback(error);
+          } catch (error) {
+            // Errors thrown by `#runReturnHandlers` are of type `Error | SerializedJsonRpcError`
+            if (error instanceof Error || isJsonRpcError(error)) {
```
[the remark this answers is not in the document]
Comment (MajorLift) [reply packages/json-rpc-engine/src/JsonRpcEngine.ts:273]: Is it very likely that return handlers won't be of type `JsonRpcEngineReturnHandler` at runtime? I feel like if we can't make any guarantees about the type of these errors at any stage in the middleware chain, then maybe we should replace all `JsonRpcEngineCallbackError` types with `unknown` or have a dedicated handling mechanism for non-jsonrpc errors. 

At least internally, `JsonRpcEngineReturnHandler` and `JsonRpcEngineNextCallback` seem to be applied without any assertions or other signs of unstable typing. If we can trust the type constraints, it seems pretty certain that the `reject` call in the `#runReturnHandlers` method will always throw a `Exclude<JsonRpcEngineCallbackError, null>`.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 6]
```diff
@@ -9,21 +9,23 @@ import type {
...
+  hasProperty,
+  isJsonRpcNotification,
+  isJsonRpcRequest,
+} from '@metamask/utils';
 
 export type JsonRpcEngineCallbackError = Error | SerializedJsonRpcError | null;
 
 export type JsonRpcEngineReturnHandler = (
-  done: (error?: JsonRpcEngineCallbackError) => void,
+  done: (error?: unknown) => void,
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:21]: New strategy: consistently type all errors as `unknown`.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 7]
```diff
@@ -9,21 +9,23 @@ import type {
...
 ) => void;
 
 export type JsonRpcEngineNextCallback = (
   returnHandlerCallback?: JsonRpcEngineReturnHandler,
 ) => void;
 
-export type JsonRpcEngineEndCallback = (
-  error?: JsonRpcEngineCallbackError,
-) => void;
+export type JsonRpcEngineEndCallback = (error?: unknown) => void;
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:28]: New strategy: consistently type all errors as `unknown`.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 8]
```diff
@@ -9,21 +9,23 @@ import type {
...
   PendingJsonRpcResponse,
 } from '@metamask/utils';
-import { hasProperty, isJsonRpcRequest } from '@metamask/utils';
+import {
+  hasProperty,
+  isJsonRpcNotification,
+  isJsonRpcRequest,
+} from '@metamask/utils';
 
 export type JsonRpcEngineCallbackError = Error | SerializedJsonRpcError | null;
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:18]: `JsonRpcEngineCallbackError` is no longer used anywhere in core, and only has two instances in mobile's `RPCMethodMiddleware.ts`.

File: packages/json-rpc-engine/src/createAsyncMiddleware.ts [hunk 9]
```diff
@@ -18,7 +21,7 @@ export type AsyncJsonrpcMiddleware<
   next: AsyncJsonRpcEngineNextCallback,
 ) => Promise<void>;
 
-type ReturnHandlerCallback = (error: null | Error) => void;
+type ReturnHandlerCallback = Parameters<JsonRpcEngineReturnHandler>[0];
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/createAsyncMiddleware.ts:24]: This definition is responsive to changes in `JsonRpcEngineReturnHandler`.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 10]
```diff
@@ -317,8 +328,8 @@ export class JsonRpcEngine extends SafeEventEmitter {
         )
       ).filter(
         // Filter out any notification responses.
-        (response) => response !== undefined,
-      ) as JsonRpcResponse<Json>[];
+        (response): response is JsonRpcResponse<Json> => response !== undefined,
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:331]: - See https://github.com/MetaMask/contributor-docs/blob/240206-typescript-guidelines-any-as/docs/typescript.md#example-f7ff4b0d-e5e9-4568-b916-5153ddd2095b

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 11]
```diff
@@ -200,9 +202,13 @@ export class JsonRpcEngine extends SafeEventEmitter {
...
 
-  // TODO: Replace `any` with type
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  handle(req: unknown, callback?: any) {
+  handle(
+    req:
+      | (JsonRpcRequest | JsonRpcNotification)[]
+      | JsonRpcRequest
+      | JsonRpcNotification,
+    callback?: (error: unknown, response: never) => void,
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:210]: `never` is used to widen the implementation signature enough to be compatible with all of the overload signatures.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 12]
```diff
@@ -403,25 +414,23 @@ export class JsonRpcEngine extends SafeEventEmitter {
...
-    }
-
-    // Handle notifications.
-    // We can't use isJsonRpcNotification here because that narrows callerReq to
-    // "never" after the if clause for unknown reasons.
-    if (this.#notificationHandler && !isJsonRpcRequest(callerReq)) {
+    } else if (
+      this.#notificationHandler &&
+      isJsonRpcNotification(callerReq) &&
+      !isJsonRpcRequest(callerReq)
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:424]: `isJsonRpcNotification` alone doesn't narrow `callerReq` to `JsonRpcNotification`.

**Review by MajorLift — COMMENTED** [review]
I attempted a new approach of replacing all `JsonRpcEngineCallbackError` with `unknown`. 

This cuts down on the diffs, makes a lot of the types consistent with how they're used in the tests, makes a lot of assertions unnecessary, and brings coverage back up to 100%. 

I think this is an appropriate scope for the current PR's objective (fix any). Implementing consistent usage of `JsonRpcEngineCallbackError` for the middleware callbacks should probably be handled as it own initiative.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (MajorLift) [reply packages/json-rpc-engine/src/JsonRpcEngine.ts]: Removed in https://github.com/MetaMask/core/pull/3906/commits/45a318e5465c6fd0999aa31361f1befa3ba8657b

File: packages/json-rpc-engine/src/createAsyncMiddleware.ts [hunk 13]
```diff
@@ -83,10 +83,8 @@ export function createAsyncMiddleware<
       } else {
         end(null);
       }
-      // TODO: Replace `any` with type
-      // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    } catch (error: any) {
-      if (returnHandlerCallback) {
+    } catch (error) {
+      if (returnHandlerCallback && error instanceof Error) {
```
[the remark this answers is not in the document]
Comment (MajorLift) [reply packages/json-rpc-engine/src/createAsyncMiddleware.ts]: Removed in https://github.com/MetaMask/core/pull/3906/commits/45a318e5465c6fd0999aa31361f1befa3ba8657b

File: packages/json-rpc-engine/jest.config.js (hunk 4 above)
Comment (MajorLift) [reply packages/json-rpc-engine/jest.config.js]: All coverage thresholds raised to 100% in https://github.com/MetaMask/core/pull/3906/commits/45a318e5465c6fd0999aa31361f1befa3ba8657b

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 14]
```diff
@@ -211,15 +217,26 @@ export class JsonRpcEngine extends SafeEventEmitter {
...
       if (callback) {
-        return this.#handleBatch(req, callback);
+        return this.#handleBatch(
+          req,
+          // This assertion is safe because of the runtime checks validating that `req` is an array and `callback` is defined.
+          // There is only one overload signature that satisfies both conditions, and its `callback` type is the one that's being asserted.
+          callback as (
+            error: unknown,
+            responses?: JsonRpcResponse<Json>[],
+          ) => void,
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:227]: Ideally, TypeScript would have better pattern-matching around overload signatures and would be capable of narrowing `callback` and `responses` so that this assertion is unnecessary.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts [hunk 15]
```diff
@@ -211,15 +217,26 @@ export class JsonRpcEngine extends SafeEventEmitter {
...
+        );
       }
       return this.#handleBatch(req);
     }
 
     if (callback) {
-      return this.#handle(req as JsonRpcRequest, callback);
+      return this.#handle(
+        req,
+        callback as (error: unknown, response?: JsonRpcResponse<Json>) => void,
```
Comment (MajorLift) [inline packages/json-rpc-engine/src/JsonRpcEngine.ts:236]: The first and second overload signatures of `handle` are the only cases where `req` is a non-array and `callback` is defined. This is assertion is safe for those overload signatures.

**Review by mcmire — COMMENTED** [review]
I just had one more comment, but this otherwise looks good to me.

File: packages/json-rpc-engine/src/JsonRpcEngine.ts (hunk 10 above)
Comment (mcmire) [reply packages/json-rpc-engine/src/JsonRpcEngine.ts:333]: Nice! Good example usage of this.

**Review by mcmire — APPROVED** [review]
Everything looks good to me now. Nice work!
