### PR TITLE
fix(assets-controllers): Prevent overlapping token rate updates

### LINKED ISSUE #3606: [assets-controllers] Prevent overlapping token rate updates
We don't currently prevent token rate updates from overlapping with each other. For example, if the same token rate update is requested twice in a row in quick succession, we will perform the update twice concurrently.

Instead we should keep track of in-progress token updates, and prevent additional redundant updates from being triggered.
If we get two calls asking for the same update, we can return the results from the first call to both callers.

### PR DESCRIPTION
**Pull request by Gudahtt**
## Explanation

Previously it was possible for two redundant token rate updates to be ongoing at the same time. This is non-optimal for performance reasons, and because the answer might change between the two requests and get persisted in the wrong order.

We now guard against this by storing in-progress updates as a private instance variable. Any redundant calls will wait on the in-progress call to finish, then return as a no-op.

## References

Fixes #3606

### `@metamask/assets-controllers`

-Fixed: Prevent overlapping token rate updates
  - This should have no impact to the API at all, it just reduces network traffic

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

File: packages/assets-controllers/src/TokenRatesController.ts [hunk 1]
```diff
@@ -358,36 +360,55 @@ export class TokenRatesController extends PollingControllerV1<
       return;
     }
 
-    const newContractExchangeRates = await this.#fetchAndMapExchangeRates({
-      tokenContractAddresses,
-      chainId,
-      nativeCurrency,
-    });
+    if (chainId in this.#inProcessExchangeRateUpdate) {
```
Comment (Gudahtt) [inline packages/assets-controllers/src/TokenRatesController.ts:363]: This assumes that the calls differ only in chain ID, but this is incorrect. They can also differ in chain ID or token addresses being queried for.

I'll fix this after I figure out why the tests are failing (they're failing for an unrelated reason).

**Comment by Gudahtt** [comment]
Tests are failing now for mysterious reasons. It seems that somehow the mocks are being shared between tests.

The new test I've added here is failing because it's saying the mock was never called, but the state update shows that it must have been. But even stranger, one of the earlier tests is failing due to a "Failed to fetch" error. This error is an artificial test error thrown by a mock used _by a different test_.

File: packages/assets-controllers/src/TokenRatesController.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/assets-controllers/src/TokenRatesController.ts]: Mostly resolved by https://github.com/MetaMask/core/pull/3635/commits/5c1e57f3070c666275fc6c91fa833b7255a6bee1, but still waiting on #3639 to be merged first so that we don't need to include token addresses in this key

File: packages/assets-controllers/src/TokenRatesController.ts [hunk 2]
```diff
@@ -145,6 +145,8 @@ export class TokenRatesController extends PollingControllerV1<
 
   #tokenPricesService: AbstractTokenPricesService;
 
+  #inProcessExchangeRateUpdate: Record<`${Hex}:${string}`, Promise<void>> = {};
```
Comment (mcmire) [inline packages/assets-controllers/src/TokenRatesController.ts:148]: Nit: Plural?

``` suggestion
  #inProcessExchangeRateUpdates: Record<`${Hex}:${string}`, Promise<void>> = {};
```

File: packages/assets-controllers/src/TokenRatesController.ts [hunk 3]
```diff
@@ -540,4 +566,60 @@ export class TokenRatesController extends PollingControllerV1<
...
+ *
+ * TODO: Migrate this to utils
+ *
+ * @param args - The arguments.
+ * @param args.suppressUnhandledRejection - This option adds an empty error handler
+ * to the Promise to suppress the UnhandledPromiseRejection error. This can be
+ * useful if the deferred Promise is sometimes intentionally not used.
+ * @returns A deferred Promise.
+ */
+function deferredPromise({
```
Comment (mcmire) [inline packages/assets-controllers/src/TokenRatesController.ts:601]: Nit: Maybe this should be called `createDeferredPromise`?

**Review by mcmire — APPROVED** [review]
A couple of nits, but this makes sense!

File: packages/assets-controllers/src/TokenRatesController.ts (hunk 2 above)
Comment (Gudahtt) [reply packages/assets-controllers/src/TokenRatesController.ts]: Good point, updated in https://github.com/MetaMask/core/pull/3635/commits/4b3bcde978833a139511c5402442c8004d0ac268

File: packages/assets-controllers/src/TokenRatesController.ts (hunk 3 above)
Comment (Gudahtt) [reply packages/assets-controllers/src/TokenRatesController.ts]: Agreed, updated in https://github.com/MetaMask/core/pull/3635/commits/d4e77d11af40db1b6b58056b3687ceca26c494f6

File: packages/assets-controllers/src/TokenRatesController.ts [hunk 4]
```diff
@@ -552,4 +577,60 @@ export class TokenRatesController extends PollingControllerV1<
...
+  let reject: DeferredPromise['reject'];
+  const promise = new Promise<void>(
+    (innerResolve: () => void, innerReject: () => void) => {
+      resolve = innerResolve;
+      reject = innerReject;
+    },
+  );
+
+  if (suppressUnhandledRejection) {
+    promise.catch((_error) => {
```
[the remark this answers is not in the document]
Comment (wachunei) [reply packages/assets-controllers/src/TokenRatesController.ts:616]: in the case [`Promise.withResolvers`](https://github.com/tc39/proposal-promise-with-resolvers) is approved as is in the current stage would this be an issue? is this something we should report as feedback?

[the remark this answers is not in the document]
Comment (wachunei) [reply packages/assets-controllers/src/TokenRatesController.ts:624]: I see, so it seems like even if `withResolvers` makes it to the final spec we would still need to wrap it and add the catch handler. I would have loved this to be easily swappable with the official implementation. 

I see there's a TODO comment to move this to utils, is there a reason not to do it now?

[the remark this answers is not in the document]
Comment (wachunei) [reply packages/assets-controllers/src/TokenRatesController.ts:624]: omg it just went to stage 4 today, what a coincidence

[the remark this answers is not in the document]
Comment (Gudahtt) [reply packages/assets-controllers/src/TokenRatesController.ts:624]: >I see there's a TODO comment to move this to utils, is there a reason not to do it now?

Yep, this is part of a set of changes that we're aiming to get included in a release candidate ASAP for release in the first week of January, so I was looking for shortcuts. I'll set a reminder for myself to migrate this

**Review by mcmire — APPROVED** [review]
Looks good!
