### PR TITLE
Fixed SafeEventEmitterProvider invalid default params

### LINKED ISSUE #4595: [safe-event-emitter-provider] Invalid default params
The `SafeEventEmitterProvider` is failing to send `net_version` requests correctly because it's using an empty object as the default params when none are provided.

While some methods do use an object for params, the vast majority use an array instead. Passing an empty object as the params for a method that has array parameters can result in failure (as is the case for `net_version`).

We should remove the default params altogether, or use an array as the default if we need to keep some default for some reason).

### PR DESCRIPTION
**Pull request by kanthesha**
## Explanation

The SafeEventEmitterProvider is failing to send net_version requests correctly because it's using an empty object as the default params when none are provided.

While some methods do use an object for params, the vast majority use an array instead. Passing an empty object as the params for a method that has array parameters can result in failure (as is the case for net_version).

## References

* Fixes #4595 

### `@metamask/eth-json-rpc-provider`

- **FIXED**: The default value for params in the request has been replaced from empty object to an empty array

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

File: packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export function convertEip1193RequestToJsonRpcRequest<
     id = uuidV4(),
     jsonrpc = '2.0',
     method,
-    params = {},
+    params = [],
```
Comment (Gudahtt) [inline packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts:38]: Have you considered omitting default params instead? It's optional in the EIP-1193 spec.

Comment (Gudahtt) [reply packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts:38]: I am not sure why that type error would happen, the property is marked as optional 🤔

Comment (mikesposito) [reply packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts:38]: > params: Params | undefined; is not assignable to the Params | Record<never, never>.

Hmm, could this happen because we still return an object with a `params` key which will have an undefined value, instead of skipping the params key altogether?

Comment (Gudahtt) [reply packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts:38]: I tried getting past this type error locally but was unable to understand the cause. It seems that there is some conflict between the types of `eip1193Request.params` and the return value `params` property. Even when I try omitting `params` when it's unset, I get this error:

```
Types of property 'params' are incompatible.
    Type 'Params' is not assignable to type '((Record<string, Json> | Json[]) & ExactOptionalGuard) & Params'.
      Type 'JsonRpcParams' is not assignable to type '((Record<string, Json> | Json[]) & ExactOptionalGuard) & Params'.
        Type 'Json[]' is not assignable to type '((Record<string, Json> | Json[]) & ExactOptionalGuard) & Params'.
          Type 'Json[]' is not assignable to type 'Json[] & ExactOptionalGuard & Params'.
            Type 'Params' is not assignable to type 'Json[] & ExactOptionalGuard & Params'.
              Type 'JsonRpcParams' is not assignable to type 'Json[] & ExactOptionalGuard & Params'.
                Type 'Json[]' is not assignable to type 'Json[] & ExactOptionalGuard & Params'.
                  Type 'Json[]' is not assignable to type 'Params'.
                    'Json[]' is assignable to the constraint of type 'Params', but 'Params' could be instantiated with a different subtype of constraint 'JsonRpcParams'.
```

Seems like a TypeScript bug. The two values have the same type, `Params`, but it's resolving one to the type constraint then saying it's not narrow enough to match `Params` 😓 .

We can workaround with a type case in the meantime though.

Comment (Gudahtt) [reply packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts:38]: Looking back at how this worked prior to #4422, we had previously omitted `params` if they were missing from the request. We had never assigned any default, until the change was introduced in #4422 that caused this bug. Continuing to omit `params` seems safer, less likely to break something.

Even if we default to `[]`, there may be some RPC endpoints that treat that as an invalid request if a method doesn't accept any params.

**Review by Gudahtt — CHANGES_REQUESTED** [review]
I think it would be safer to omit rather than using any default, see [here](https://github.com/MetaMask/core/pull/4603/files#r1715308965) for details

File: packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts:38]: That is what I understood @mikesposito 's suggestion to be; that's what I tried locally when I encountered the type error that I posted.

My most recent comment had a typo in it, apologies for the confusion, it is now edited. My most recent suggestion was to use a type cast to get around the type error.

Though probably we should use `// ts-expect-error` instead of a cast, and explain the error to the best of our ability, and why we cannot workaround it.

File: packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts [hunk 2]
```diff
@@ -31,18 +31,19 @@ export function convertEip1193RequestToJsonRpcRequest<
 >(
   eip1193Request: Eip1193Request<Params>,
 ): JsonRpcRequest<Params | Record<never, never>> {
```
Comment (Gudahtt) [inline packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts:33]: Hmm, this return type is invalid. The `Record<never, never>` does not belong here, no possible return value is represented by that type. Yet if we remove it, we get the type error I referenced in the other thread. How odd.

Maybe we can fix it in a later PR, since it's a pre-existing issue. This type is used later in this file as well.

File: packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/eth-json-rpc-provider/src/safe-event-emitter-provider.ts]: The suggestion does work, but only due to a pre-existing invalid type that I had fixed locally when testing. Details here: https://github.com/MetaMask/core/pull/4603#discussion_r1715378903
