### PR TITLE
Remove `for..in` loops and reenable eslint rules: `guard-for-in`, `no-for-in-array`

### LINKED ISSUE #1866: Remove `for..in` loops and reenable ESLint rules: `guard-for-in`, `no-for-in-array`
`for..in` loops [iterate over the entire prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) and are discouraged because they can cause unexpected behavior. 

Our ESLint ruleset also guards against them by default, but the relevant rules are currently disabled and there is some `for..in` loop usage in the core monorepo. 

- [x] Remove all `for..in` loops from the core monorepo.
- [x] Document safer alternatives to `for..in` loops in various use cases.
- [x] Reenable the ESLint rules `guard-for-in` and `@typescript-eslint/no-for-in-array`.

### PR DESCRIPTION
**Pull request by MajorLift**
## Explanation

`for..in` loops [iterate over the entire prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) and are discouraged because they can cause unexpected behavior. Our ESLint ruleset also guards against them by default.

`for..in` loops are sometimes used because they are useful for introspection of object properties, but there are safer alternatives:

- Use `for..of Object.keys()` if the index signature is just `string`.
- When inspecting property keys with signatures that are more specific than `string`, use `getKnownPropertyNames()` from `@metamask/utils` as a safe alternative to `for..in`.
- Use `for..of Object.keys(obj) as (keyof typeof obj)[])` for stronger typing of the index signature if `obj` properties are generic, populated at runtime, or otherwise not fully determinable by `getKnownPropertyNames()`.
- To access array indices from a `for..of` loop, use the `Array.prototype.entries()` method.

This PR removes all `for..in` loops in the core monorepo, and resolves all conflicts with the ESLint rules `guard-for-in` and `@typescript-eslint/no-for-in-array`. Some typing improvements are also introduced.

## References

- Closes #1866 

## Changelog

No consumer-facing changes other than the reenabled linter rules.

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

File: packages/assets-controllers/src/TokenBalancesController.ts [hunk 1]
```diff
@@ -116,7 +116,7 @@ export class TokenBalancesController extends BaseController<
     }
     const { tokens } = this.config;
     const newContractBalances: { [address: string]: BN } = {};
-    for (const i in tokens) {
+    for (const [i] of tokens.entries()) {
```
Comment (MajorLift) [inline packages/assets-controllers/src/TokenBalancesController.ts:119]: To access array indices in a `for..of` loop, use the new `Array.prototype.entries()` method.

File: packages/assets-controllers/src/TokenDetectionController.ts [hunk 2]
```diff
@@ -235,7 +235,7 @@ export class TokenDetectionController extends BaseController<
     );
     const { tokenList } = this.getTokenListState();
     const tokensToDetect: string[] = [];
-    for (const address in tokenList) {
+    for (const address of Object.keys(tokenList)) {
```
Comment (MajorLift) [inline packages/assets-controllers/src/TokenDetectionController.ts:238]: Use `for..of Object.keys()` if the index signature is just `string`.

File: packages/transaction-controller/src/utils.ts [hunk 3]
```diff
@@ -36,10 +37,9 @@ const NORMALIZERS: { [param in keyof TransactionParams]: any } = {
  */
 export function normalizeTxParams(txParams: TransactionParams) {
   const normalizedTxParams: TransactionParams = { from: '' };
-  let key: keyof TransactionParams;
-  for (key in NORMALIZERS) {
-    if (txParams[key as keyof TransactionParams]) {
-      normalizedTxParams[key] = NORMALIZERS[key](txParams[key]) as never;
+  for (const key of getKnownPropertyNames(NORMALIZERS)) {
```
Comment (MajorLift) [inline packages/transaction-controller/src/utils.ts:40]: When inspecting property keys with signatures that are more specific than `string`, use `getKnownPropertyNames()` from `@metamask/utils` as a safe alternative to `for..in`.

File: packages/preferences-controller/src/PreferencesController.ts [hunk 4]
```diff
@@ -162,15 +162,15 @@ export class PreferencesController extends BaseController<
     const { identities, lostIdentities } = this.state;
     const newlyLost: { [address: string]: ContactEntry } = {};
 
-    for (const identity in identities) {
+    for (const identity of Object.keys(identities)) {
       if (!addresses.includes(identity)) {
         newlyLost[identity] = identities[identity];
         delete identities[identity];
       }
     }
```
Comment (MajorLift) [inline packages/preferences-controller/src/PreferencesController.ts:170]: Use `for..of Object.keys()` if the index signature is just `string`.

File: packages/transaction-controller/src/utils.ts [hunk 5]
```diff
@@ -36,10 +37,9 @@ const NORMALIZERS: { [param in keyof TransactionParams]: any } = {
...
+    if (txParams[key]) {
+      normalizedTxParams[key] = NORMALIZERS[key](txParams[key]);
     }
   }
   return normalizedTxParams;
```
Comment (MajorLift) [inline packages/transaction-controller/src/utils.ts:45]: When inspecting property keys with signatures that are more specific than `string`, use `getKnownPropertyNames()` from `@metamask/utils` as a safe alternative to `for..in`.

File: packages/base-controller/src/BaseController.ts [hunk 6]
```diff
@@ -120,17 +120,17 @@ export class BaseController<C extends BaseConfig, S extends BaseState> {
...
-      for (const key in config) {
+      for (const key of Object.keys(config) as (keyof C)[]) {
         /* istanbul ignore else */
         if (typeof this.internalConfig[key] !== 'undefined') {
-          this.internalConfig[key] = config[key] as any;
-          (this as any)[key as string] = config[key];
+          this.internalConfig[key] = (config as C)[key];
+          (this as any)[key] = config[key];
         }
       }
```
Comment (MajorLift) [inline packages/base-controller/src/BaseController.ts:135]: Use `for..of Object.keys(obj) as (keyof typeof obj)[])` for stronger typing of the index signature if `obj` properties are generic, populated at runtime, or otherwise not fully determinable by `getKnownPropertyNames()`.

File: packages/assets-controllers/src/TokenBalancesController.ts [hunk 7]
```diff
@@ -116,7 +116,7 @@ export class TokenBalancesController extends BaseController<
...
       const { address } = tokens[i];
       try {
         newContractBalances[address] = await this.getERC20BalanceOf(
```
Comment (MajorLift) [inline packages/assets-controllers/src/TokenBalancesController.ts:122]: To access array indices in a `for..of` loop, use the new `Array.prototype.entries()` method.

Comment (mcmire) [reply packages/assets-controllers/src/TokenBalancesController.ts:122]: Hmm, it seems like we don't actually need the index here. Perhaps we ought to iterate over the values in the array instead?

File: packages/base-controller/src/BaseController.ts [hunk 8]
```diff
@@ -120,17 +120,17 @@ export class BaseController<C extends BaseConfig, S extends BaseState> {
         ? (config as C)
         : Object.assign(this.internalConfig, config);
 
-      for (const key in this.internalConfig) {
+      for (const key of Object.keys(this.internalConfig) as (keyof C)[]) {
         if (typeof this.internalConfig[key] !== 'undefined') {
-          (this as any)[key as string] = this.internalConfig[key];
+          (this as any)[key] = this.internalConfig[key];
         }
       }
```
Comment (mcmire) [inline packages/base-controller/src/BaseController.ts:127]: Can we iterate over `Object.entries` instead? (We also don't need to use `typeof` to check for `undefined`, so we can simplify that too.)

``` suggestion
      for (const [key, value] of Object.entries(this.internalConfig)) {
        if (value !== undefined) {
          (this as any)[key] = value;
        }
      }
```

File: packages/base-controller/src/BaseController.ts [hunk 9]
```diff
@@ -120,17 +120,17 @@ export class BaseController<C extends BaseConfig, S extends BaseState> {
...
     } else {
-      for (const key in config) {
+      for (const key of Object.keys(config) as (keyof C)[]) {
```
Comment (mcmire) [inline packages/base-controller/src/BaseController.ts:129]: This one is a weird one and I couldn't get it to be any better than this :(

File: packages/preferences-controller/src/PreferencesController.ts [hunk 10]
```diff
@@ -162,15 +162,15 @@ export class PreferencesController extends BaseController<
...
 
     if (Object.keys(newlyLost).length > 0) {
-      for (const key in newlyLost) {
+      for (const key of Object.keys(newlyLost)) {
         lostIdentities[key] = newlyLost[key];
       }
     }
```
Comment (mcmire) [inline packages/preferences-controller/src/PreferencesController.ts:176]: Can we iterate over `Object.entries` here? Also we don't need to check for `Object.keys(...).length` first.

``` suggestion
    for (const [key, value] of Object.entries(newlyLost)) {
      lostIdentities[key] = value;
    }
```

**Review by mcmire — COMMENTED** [review]
Thanks for doing this! Just a few suggestions.

File: packages/base-controller/src/BaseController.ts (hunk 8 above)
Comment (MajorLift) [reply packages/base-controller/src/BaseController.ts:127]: Nice! This is much cleaner.

File: packages/base-controller/src/BaseController.ts (hunk 9 above)
Comment (MajorLift) [reply packages/base-controller/src/BaseController.ts:129]: I think `Object.entries()` doesn't work if the key needs to be more specific than `string`.

File: packages/preferences-controller/src/PreferencesController.ts (hunk 10 above)
Comment (mcmire) [reply packages/preferences-controller/src/PreferencesController.ts]: Oh really? Weird. Yeah, since it's less than a percentage point, I think it's okay to adjust the threshold value.

File: packages/base-controller/src/BaseController.ts (hunk 9 above)
Comment (mcmire) [reply packages/base-controller/src/BaseController.ts:129]: Yeah, this one is different too I think because we're using the keys from one object to operate on another object and both objects have specific types for their keys.

**Review by mcmire — APPROVED** [review]
Looks great!
