### PR TITLE
fix: remove usage current network from tokens controller

### LINKED ISSUE #5580: [GNS] Remove usage of #chainId and current selected network from TokensController
In `tokenControllers`, the private property `#chainId` currently falls back to the `selectedNetwork`, as seen in the `#onNetworkDidChange` method. This implicit fallback is not needed the removal of the global network selector

### 🎯 Goal

- Remove the `#chainId` private property entirely
- Refactor all functions that use `#chainId` to **require `chainId` or `clientNetworkId` as an explicit, mandatory parameter**

### PR DESCRIPTION
**Pull request by salimtb**
## Explanation

The current implementation of `TokensController` relies heavily on a single selected network (`chainId`) as an instance property, which makes multi-chain token handling brittle and hard to scale. Additionally, some token operations unintentionally assume a persistent network context, introducing potential bugs when switching networks or performing actions concurrently across different chains.

This PR refactors the `TokensController` to eliminate reliance on an internal `#chainId` property. Instead, all methods that require a network context now accept a `networkClientId` as an explicit parameter. This improves the controller’s ability to operate safely and predictably in a multi-chain environment.

The `#onNetworkDidChange` logic and associated subscription were removed since network changes are now handled at the method level with explicit `networkClientId` parameters. All relevant internal state mutations and token metadata fetches are scoped to the appropriate chain via the `networkClientId -> chainId` mapping.

This refactor is part of a broader initiative to support simultaneous multi-chain state handling across the codebase (see recent changes to `TokenRatesController` and `AccountTrackerController`).

integration with UI:
extension: https://github.com/MetaMask/metamask-extension/pull/32274
mobile: https://github.com/MetaMask/metamask-mobile/pull/14913

## References
* Fixes #5580 

### `@metamask/assets-controllers`

- **UPDATE:** Refactor `TokensController` to support handling multiple chains in parallel. All network-dependent methods now require an explicit `networkClientId` parameter, enabling token operations to be fully scoped to a specific chain. This improves reliability and predictability when managing tokens across different networks.
- **BREAKING:** Remove internal reliance on a single `chainId` instance property in `TokensController`. All chain-specific logic has been externalized. Consumers must now explicitly pass a `networkClientId` to methods that interact with the token state. This change may require updates on the client side to ensure correct chain context is provided during token actions.

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've communicated my changes to consumers by [updating changelogs for packages I've changed](https://github.com/MetaMask/core/tree/main/docs/contributing.md#updating-changelogs), highlighting breaking changes as necessary
- [ ] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

### CODE REVIEW

File: packages/assets-controllers/src/TokensController.ts [hunk 1]
```diff
@@ -223,11 +218,6 @@ export class TokensController extends BaseController<
       this.#onSelectedAccountChange.bind(this),
     );
 
-    this.messagingSystem.subscribe(
-      'NetworkController:networkDidChange',
```
Comment (Prithpal-Sooriya) [inline packages/assets-controllers/src/TokensController.ts:227]: Awesome! Do we still need this in the allowedEvents?

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Review by Prithpal-Sooriya — APPROVED** [review]
