### PR TITLE
fix: Compress transaction history upon update

### LINKED ISSUE #4549: [transaction-controller] Boundless growth of transaction history
Each transaction has a `history` property, which tracks changes to the transaction state. This history doesn't currently have a maximum limit and can grow indefinitely, effectively becoming a memory leak. Unfortunately it can grow rather rapidly as well, because it tracks changes to the transaction `warning.error` state which can update multiple times in a single pending transaction status check.

We should prevent this history from growing unbounded, and maybe replace or severely limit its size in general.

### PR DESCRIPTION
**Pull request by Gudahtt**
## Explanation

The TransactionController has been updated to compress transaction history if it exceeds the max transaction history size, which for now has been set to 100. Each time a new entry is added to a transaction history already at max size, we merge two entries to make room for the new one.

Note that we never compress entries used for display in the transaction activity log, because compressing those entries might hide events that we want to display. If there are no non-displayed entries to compress, history is allowed to exceed the max size.

This is a temporary solution to prevent unbounded growth of the transaction history. While technically it is still unbounded at this level because we don't strictly limit displayed history entries, we don't know of any cases where displayed entries can be repeated a significant number of times, so this will solve that problem in practice.

## References

Fixes #4549

## Changelog

For the `@metamask/transaction-controller` package:
```markdown
### Added

- Add `DISPLAYED_TRANSACTION_HISTORY_PATHS` constant, representing the transaction history paths that may be used for display ([#4555](https://github.com/MetaMask/core/pull/4555))
  - This was exported so that it might be used to ensure display logic and internal history logic remains in-sync.
  - Any paths listed here will have their timestamps preserved. Unlisted paths may be compressed by the controller to minimize history size, losing the timestamp.
- Add `MAX_TRANSACTION_HISTORY_LENGTH` constant, representing the expected maximum size of the `history` property for a given transaction ([#4555](https://github.com/MetaMask/core/pull/4555))
  - Note that this is not strictly enforced, the length may exceed this number of all entries are "displayed" entries, but we expect this to be extremely improbable in practice.

### Fixed

- Prevent transaction history from growing endlessly in size ([#4555](https://github.com/MetaMask/core/pull/4555))
```
## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

File: packages/transaction-controller/src/utils/history.ts [hunk 1]
```diff
@@ -7,6 +7,22 @@ import type {
...
 
+/**
+ * The maximum allowed length of the `transaction.history` property.
+ */
+export const MAX_HISTORY_LENGTH = 100;
+
+/**
+ * A list of the paths used in the display of a transaction activity log.
+ */
+export const ACTIVITY_LOG_HISTORY_PATHS = [
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.ts:18]: Is there an argument to decouple, even conceptually, from what the clients chose to do with the history data?

Could this be `UNCOMPRESSABLE_HISTORY_PATHS` for example?

Logically, we could also accept these as a constructor argument but that feels excessive if we ultimately plan to remove the history in the long term.

File: packages/transaction-controller/src/utils/history.ts [hunk 2]
```diff
@@ -40,16 +56,99 @@ export function updateTransactionHistory(
...
   const currentState = snapshotFromTransactionMeta(transactionMeta);
   const previousState = replayHistory(transactionMeta.history);
-  const historyEntry = generateHistoryEntry(previousState, currentState, note);
+  const newHistoryEntry = generateHistoryEntry(
+    previousState,
+    currentState,
+    note,
+  );
+
+  if (newHistoryEntry.length > 0) {
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.ts:65]: Minor, could we early return here instead so the core logic isn't nested in a block?

File: packages/transaction-controller/src/utils/history.ts [hunk 3]
```diff
@@ -40,16 +56,99 @@ export function updateTransactionHistory(
...
+    // Casts required here because this list has two separate types of entries:
+    // TransactionMeta and TransactionHistoryEntry. The only TransactionMeta is the first
+    // entry, but TypeScript loses that type information when `slice` is called for some reason.
+    let updatedHistory = transactionMeta.history.slice() as TransactionHistory;
+    updatedHistory.push(newHistoryEntry);
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.ts:70]: Minor, could this be achieved with a `...` instead?

File: packages/transaction-controller/src/utils/history.ts [hunk 4]
```diff
@@ -40,16 +56,99 @@ export function updateTransactionHistory(
...
+
+  const firstNonDisplayedEntryIndex = historyEntries.findIndex(
+    (historyEntry) => {
+      return !historyEntry.some(({ path }) =>
+        ACTIVITY_LOG_HISTORY_PATHS.includes(path),
+      );
+    },
+  );
+
+  // If no non-diplayed entry is found, let history exceed max size.
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.ts:109]:
```suggestion
  // If no non-displayed entry is found, let history exceed max size.
```

File: packages/transaction-controller/src/utils/history.ts [hunk 5]
```diff
@@ -40,16 +56,99 @@ export function updateTransactionHistory(
...
+): TransactionHistory {
+  const initialEntry = transactionHistory[0];
+  // Casts required here because this list has two separate types of entries:
+  // TransactionMeta and TransactionHistoryEntry. The only TransactionMeta is the first
+  // entry, but TypeScript loses that type information when `slice` is called for some reason.
+  const historyEntries = transactionHistory.slice(
+    1,
+  ) as TransactionHistoryEntry[];
+
+  const firstNonDisplayedEntryIndex = historyEntries.findIndex(
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.ts:101]: Forgive me if I'm misunderstanding, but we're looking for the first entry without any of the activity paths, and merging it (ideally) with the next entry.

But in a worst case scenario, could this have negligible impact on size if both entries update entirely different fields with different operations?

If we assume we likely reach the history limit when some kind of loop starts adding duplicate entries, then would it be more impactful to start merging from the end? Since that's more likely to reduce the net state size?

File: packages/transaction-controller/src/utils/history.ts [hunk 6]
```diff
@@ -40,16 +56,99 @@ export function updateTransactionHistory(
...
+  // If no non-diplayed entry is found, let history exceed max size.
+  // TODO: Move data used for display to another property, so that we can more reliably limit
+  // history size or remove it altogether.
+  if (firstNonDisplayedEntryIndex === -1) {
+    return transactionHistory;
+  }
+
+  // If a non-displayed entry is found that we can remove, merge it with another entry.
+  // The entry we're merging with might be a "displayed" entry, but that's OK, merging more changes
+  // in does not break our display logic.
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.ts:118]: To clarify, are we saying that an entry with the activity paths can have other non-activity fields in, but we don't support multiple activity paths in the same entry?

It would indeed be nice to fix this with a single package upgrade, but is it a trade off since the current UI logic could theoretically be simplified to read the data from the same entry and therefore simplify this compression logic?

File: packages/transaction-controller/src/utils/history.ts [hunk 7]
```diff
@@ -40,16 +56,99 @@ export function updateTransactionHistory(
...
+  ]);
+  const afterMergeState = replayHistory([
+    beforeMergeState,
+    historyEntries[firstIndexToMerge],
+    historyEntries[firstIndexToMerge + 1],
+  ]);
+  const mergedHistoryEntry = generateHistoryEntry(
+    beforeMergeState,
+    afterMergeState,
+    `${String(historyEntries[firstIndexToMerge][0].note)}, ${String(
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.ts:143]: Minor, since we use `historyEntries[firstIndexToMerge]` and `historyEntries[firstIndexToMerge + 1]` above also, could we define variables for them?

File: packages/transaction-controller/src/utils/history.test.ts [hunk 8]
```diff
@@ -0,0 +1,372 @@
...
+
+import {
+  type TransactionHistory,
+  TransactionStatus,
+  type TransactionMeta,
+  type TransactionHistoryEntry,
+} from '../types';
+import { MAX_HISTORY_LENGTH, updateTransactionHistory } from './history';
+
+describe('History', () => {
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.test.ts:13]: We currently test the history at the controller level in `TransactionController.test.ts` but this definitely feels warranted now given the extra logic.

File: packages/transaction-controller/src/utils/history.test.ts [hunk 9]
```diff
@@ -0,0 +1,372 @@
...
+            }),
+            // This is the changed value
+            txParams: { from: generateAddress(123) },
+          },
+        });
+        // Validate that last history entry is correct
+        // Assertion used because we know the history is set here.
+        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+        const mockHistoryLength = mockTransaction.history!.length;
+        expect(mockTransaction.history?.[mockHistoryLength - 1]).toStrictEqual([
```
Comment (matthewwalsh0) [inline packages/transaction-controller/src/utils/history.test.ts:92]: Minor, but do we need this if it's ultimately testing a test helper?

Could we at least create a dedicated test for it so it's not duplicated in each test?

**Review by matthewwalsh0 — CHANGES_REQUESTED** [review]

File: packages/transaction-controller/src/utils/history.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.ts:18]: >Logically, we could also accept these as a constructor argument but that feels excessive if we ultimately plan to remove the history in the long term.

Yeah, this was my thought exactly.

We could certainly rename it. But I was trying to capture _why_ we're not compressing it. Really these entries _can_ be compressed just as well as the others. We'd lose some information (the timestamp), but that's true of the others as well. So calling them "uncompressable" doesn't seem exactly right.

We could call it something more generic like `DISPLAYED_HISTORY_PATHS` - paths used for display by clients. Any other ideas?

File: packages/transaction-controller/src/utils/history.ts (hunk 2 above)
Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.ts]: Good idea, done in fffcd212

I had missed this because this was pre-existing code, the diff makes it seem new only because I renamed `newHistoryEntry`. But that's fine, this is nicer.

File: packages/transaction-controller/src/utils/history.ts (hunk 3 above)
Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.ts]: Yes, it could. I was trying to avoid the need for a type cast here, but it didn't work, so I'll switch it back to `...`.

Done in ee3692d0

File: packages/transaction-controller/src/utils/history.ts (hunk 5 above)
Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.ts:104]: >But in a worst case scenario, could this have negligible impact on size if both entries update entirely different fields with different operations?

True, but there are only so many fields (certainly fewer than 100, which is the limit set at the moment). They will have to overlap eventually, at which point it'll save space.

100 or even 1000 entries won't have a huge impact on memory usage, these are not large entries. This is really just meant to stop growth. It's certainly not optimal, optimal would be to stop using this for display, hopefully we'll do that soon.

>If we assume we likely reach the history limit when some kind of loop starts adding duplicate entries, then would it be more impactful to start merging from the end? Since that's more likely to reduce the net state size?

In that scenario, starting at the beginning still gets us there eventually. I figured that starting at the beginning would leave more useful diagnostic information (e.g. the more recent actions would be more relevant to what the user did when they took a state snapshot). But I'm not really sure.

File: packages/transaction-controller/src/utils/history.ts (hunk 6 above)
Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.ts:121]: >but we don't support multiple activity paths in the same entry?

It's not that we don't support multiple paths in the same entry. It's that we only have one timestamp per entry. There's a bit on that here: https://github.com/MetaMask/metamask-extension/blob/c2043772729b52d6f4f4c09f32ead95bdf50b6dc/ui/components/app/transaction-activity-log/transaction-activity-log.util.js#L111

See that we do iterate through every entry, but the comment suggests that each change in an entry "might not" have a timestamp, but the first one always does. If we examine the code here, we can see that the timestamp is present only on the first entry. The timestamp is an important part of how these get displayed.

The goal here was to be non-destructive with displayed data, so I was avoiding merging two displayed entries because that would lose a timestamp.

File: packages/transaction-controller/src/utils/history.test.ts (hunk 9 above)
Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.test.ts:92]: Ah, so this is something I added for myself because I was having trouble telling what the test I wrote did 😅 . It wasn't meant to test the helper function exactly, just to check that I had called it correctly. I had more than one off-by-one error in writing this. I added this validation so that I could read the piece of the history relevant to the test, the very last one.

Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.test.ts:92]: This is noisy though. I'll remove these non-null assertions at least, those are bothersome.

Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.test.ts:90]: Alright it's a bit less noisy in 3a9cee7e, let me know what you think

Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.test.ts]: Ok, fixed in 441acde

File: packages/transaction-controller/src/utils/history.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/transaction-controller/src/utils/history.ts]: I have renamed it in a1cd8d91 to be `DISPLAYED_TRANSACTION_HISTORY_PATHS`, which is at least more consistent with other internal variables, and a bit less specific to how it's used (the description also now says that these paths "may" be displayed, not that it's certain they are).

**Review by matthewwalsh0 — DISMISSED** [review]

**Comment by Gudahtt** [comment]
@metamaskbot publish-preview

**Comment by Gudahtt** [comment]
Rebased to resolve changelog conflict

**Review by matthewwalsh0 — APPROVED** [review]
