### PR TITLE
fix(base-controller): Fix selectors initial value comparison

### LINKED ISSUE #3649: [base-controller] ControllerMessenger selectors skip initial value
The ControllerMessenger `subscribe` function accepts an optional "selector" which can act like a Redux selector in that it narrows the state to just the subset that is of interest to that subscriber. The subscriber isn't invoked unless that specific piece of state is updated.

However, these selectors don't consider the initial state. They will always run upon the first state change, regardless what has changed.

We should update the `ControllerMessenger` to cache the initial state as well, so that we can use that for a point of comparison even on the first update.

### PR DESCRIPTION
**Pull request by Gudahtt**
## Explanation

The "selectors" feature of the `ControllerMessenger` did not work correctly for the first event published after subscribing, because the original value of the payload (at time of subscribing) was not available for comparison.

To address this, a `registerInitialEventPayload` method has been added to the `ControllerMessenger` and `RestrictedControllerMessenger`. This allows registering a function that returns the "event payload state" at a given time, which is used internally by the `subscribe` method to correctly initialize the payload cache when a subscriber with a selector is added. This ensures that the selector works correctly even for the initial state change, in that it will return the correct previous value, and not fire at all if the selected piece of state is unchanged.

In a later PR, `BaseControllerV2` can be updated to register an event payload for the `stateChange` event. This will fix this flaw for the `stateChange` event of each controller.

## References

Fixes #3649

### `@metamask/base-controller`

- Added: Add `registerInitialEventPayload` to `ControllerMessenger` and `RestrictedControllerMessenger`
  - This allows registering an event payload function for an event, which has the benefit of ensuring the "subscription selector" feature works correctly the first time the event is fired after subscribing.
- Fixed: Fix `subscribe` method selector support on first publish
  - An event with a registered initial event payload function will work better with selectors, in that it will correctly compare with the initial selected state and return the previous value the first time it's published. Without this, the initial published event will always return `undefined` as the previous value.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by Gudahtt** [comment]
The base controller has been updated in #3702

See that PR for a demonstration of how this would work

File: packages/base-controller/src/ControllerMessenger.ts [hunk 1]
```diff
@@ -129,6 +129,16 @@ export class ControllerMessenger<
 
   readonly #events = new Map<Event['type'], EventSubscriptionMap<Event>>();
 
+  /**
+   * A map of functions for getting the initial event payload.
+   *
+   * Used only for events that represent state changes.
+   */
+  readonly #getEventPayload = new Map<
```
Comment (mcmire) [inline packages/base-controller/src/ControllerMessenger.ts:137]: The name of this implies that this is a function, not a map of event types to functions.

It's not much better but perhaps `#eventPayloadGetters` makes more sense? Or `#initialEventPayloadGetters`, to more closely match how this is used in practice?

File: packages/base-controller/src/ControllerMessenger.ts [hunk 2]
```diff
@@ -210,6 +220,27 @@ export class ControllerMessenger<
...
+   *
+   * This is used for events that represent a state change, where the payload is the state.
+   * Registering a function for getting the payload allows event selectors to have a point of
+   * comparison the first time state changes.
+   *
+   * @param args - The arguments to this function
+   * @param args.eventType - The event type to register a payload for.
+   * @param args.getPayload - A function for retrieving the event payload.
+   */
+  registerInitialEventPayload<EventType extends Event['type']>({
```
Comment (mcmire) [inline packages/base-controller/src/ControllerMessenger.ts:234]: It seems that we are only extending the API of the messenger for a very specific use case. Do we expect consumers to call this on its own, or is this really something that we will only call internally? If the former, what are your thoughts on tying this more closely to that use case by adding a fourth argument to `subscribe` that would allow consumers to specify an initial payload getter when subscribing? If the latter, then what do you think about adding a note in the docs here — that if you want to use this for a particular event, make sure to call it ahead of any code that registers subscriptions.

**Review by mcmire — COMMENTED** [review]
Left two comments, but overall this makes sense.

File: packages/base-controller/src/ControllerMessenger.ts (hunk 2 above)
Comment (Gudahtt) [reply packages/base-controller/src/ControllerMessenger.ts:234]: We could make it a fourth parameter to `subscribe`, but that'd put the responsibility on each subscriber to know how to get the initial state, and it'd make using selectors a lot more verbose (and would require an additional action to get the initial state).


Whereas with the `registerInitialEventPayload` solution, the publisher of the event is also responsible for registering this "get payload" function. This seems ideal because the publisher is the one who can be most confident what the state will be at any given time, and it keeps the responsibility in a single place.

>Do we expect consumers to call this on its own, or is this really something that we will only call internally?

This is something that would be called in controller constructors, similar to the action registrations. Before any publishing happens.

It doesn't really matter whether this registration occurs before or after subscriptions. It just has to happen before publishing. Just like the action handlers need to be registered before calling.

I'm not sure if it'll have a use beyond the state event. Maybe if we have a controller that is exposing third-party state, it might be relevant (e.g. something that is proxying on-chain or remote API state).

File: packages/base-controller/src/ControllerMessenger.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/base-controller/src/ControllerMessenger.ts:137]: Good point, I'll go with `initialEventPayloadGetters`

**Review by mcmire — APPROVED** [review]
Looks good!

**Comment by Gudahtt** [comment]
I'm going to wait until https://github.com/MetaMask/core/pull/3713 is merged and released before merging this, to keep the releases more focused.
