### PR TITLE
Log when we fail to connect to a network

### LINKED ISSUE #1460: [network controller] Log when we fail to connect to a network
The `lookupNetwork` method of the network controller should include console warnings for all branches where we fail to connect to a network. This would be very useful when investigating bug reports.

Failing to connect to a network is in a class of errors that is expected, but still noteworthy and potentially related to a bug. Console warnings are a good solution for these situations; they provide hints in the console for anyone investigating, and they show up in Sentry if a real error is thrown in the vicinity of the warning.

Rather than using `console.log` directly, we should consider updating the controller to accept a `loglevel` instance, so that we can use that to print console warnings while leaving the client in full control of whether these logs are enabled or not.

### PR DESCRIPTION
**Pull request by kanthesha**
## Explanation
The `lookupNetwork` and `lookupNetworkByClientId` methods of the network controller now includes console warnings for all branches where we fail to connect to a network. This would be very useful when we investigating bug reports.

## References

Fixes #1460 

### `@metamask/network-controller`

- **Added**: Display console warnings when it fails to connect to a network

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by mcmire** [comment]
The ticket says: 

> Rather than using `console.log` directly, we should consider updating the controller to accept a `loglevel` instance, so that we can use that to print console warnings while leaving the client in full control of whether these logs are enabled or not.

It seems that in order to satisfy this desire, perhaps we ought to have the controller take a Loglevel object as a controller option?

File: packages/network-controller/src/NetworkController.ts [hunk 1]
```diff
@@ -431,12 +432,17 @@ export class NetworkController extends BaseController<
...
+  #logLevel: RootLogger | undefined;
+
+  constructor(
+    {
+      messenger,
+      state,
+      infuraProjectId,
+      trackMetaMetricsEvent,
+    }: NetworkControllerOptions,
+    logLevel?: RootLogger,
```
Comment (mcmire) [inline packages/network-controller/src/NetworkController.ts:444]: `logLevel` sounds like it's the level of a logger (like "debug" or "info"). I know the package is called `loglevel`, but maybe we should call it something else? The [advice](https://github.com/pimterry/loglevel?tab=readme-ov-file#methods) given in the `loglevel` README is to call it `log`, so perhaps that's what we should go with?

**Review by mcmire — COMMENTED** [review]
One more suggestion!

File: packages/network-controller/src/NetworkController.ts (hunk 1 above)
Comment (mcmire) [reply packages/network-controller/src/NetworkController.ts:444]: Also, what are your thoughts on adding this argument to the list of options rather than as a separate argument?

Comment (mcmire) [reply packages/network-controller/src/NetworkController.ts:444]: Oh, right. What about `logger` then? Is that less confusing?

Comment (Gudahtt) [reply packages/network-controller/src/NetworkController.ts]: Another option would be to rename the existing `log` to be something like `debugLog`. It is used exclusively for debug logging

File: packages/network-controller/src/NetworkController.ts [hunk 2]
```diff
@@ -431,12 +432,17 @@ export class NetworkController extends BaseController<
     | AutoManagedNetworkClient<CustomNetworkClientConfiguration>
     | AutoManagedNetworkClient<InfuraNetworkClientConfiguration>;
 
-  constructor({
-    messenger,
-    state,
-    infuraProjectId,
-    trackMetaMetricsEvent,
-  }: NetworkControllerOptions) {
+  #loglevelLogger: RootLogger | undefined;
```
Comment (Gudahtt) [inline packages/network-controller/src/NetworkController.ts:435]: Is `RootLogger` the correct type to use here? This implies that the global logger instance would need to be passed in. But the reason for suggesting `loglevel` in the first place was to allow the client to configure logging for each controller independently, which means that we'd want to ask for a non-root logger. I think the `Logger` type is what we want here.

File: packages/network-controller/src/NetworkController.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/network-controller/src/NetworkController.ts]: Not super important, but `log` does seem like a better name to me.

Comment (Gudahtt) [reply packages/network-controller/src/NetworkController.ts]: >My thought process was, it's not directly related to functionality of NetworkController, but required for debugging. So thought, better to be outside controller options.

Hmm, this seems like a misunderstanding. We have a separate logger for debugging. This one is meant for runtime logs that would be present in production. This would be for logs that we would expect to be present in user reports and on Sentry.

Though either way, I would recommend that we keep using this "options bag" pattern of passing in parameters. This is meant as a way of using named parameters, it wasn't intended to be a grouping with any semantic meaning. Named parameters are just nicer ergonomically, you can see what an option is when you pass it in. e.g. `func({ log: foo })` is clearer than `func(foo)`, it's slightly self-documenting.

We have dissimilar options/arguments in the same object in many of our APIs already.

File: packages/network-controller/src/NetworkController.ts [hunk 3]
```diff
@@ -699,6 +707,13 @@ export class NetworkController extends BaseController<
       );
       updatedNetworkStatus = NetworkStatus.Available;
     } catch (error) {
+      this.#loglevelLogger?.warn(
+        'NetworkController: lookupNetworkByClientId: ',
```
Comment (Gudahtt) [inline packages/network-controller/src/NetworkController.ts:711]: This appear to be debug logs, which is not what this logger was intended for. We have another logger for debug logs already.

This one was intended to be for notable events that we would want to appear in logs in production, such as operational errors.

File: packages/network-controller/src/NetworkController.ts [hunk 4]
```diff
@@ -431,12 +432,17 @@ export class NetworkController extends BaseController<
...
+  #log: Logger | undefined;
+
+  constructor(
+    {
+      messenger,
+      state,
+      infuraProjectId,
+      trackMetaMetricsEvent,
+    }: NetworkControllerOptions,
+    log?: Logger,
```
Comment (mcmire) [inline packages/network-controller/src/NetworkController.ts:444]: I think we still want this to be in the set of options and not a separate argument, yes @Gudahtt?

**Review by mcmire — APPROVED** [review]
LGTM.
