### PR TITLE
Fix/default network

### LINKED ISSUE #843: Ensure initial networkType/chainID is passed into each controller
Many controllers initialize with the `chainId` or `networkType` set to `1` or `MAINNET` respectively, because that is the default network. The configuration gets updated whenever the network state changes, but until the first state change it might be invalid.

As a general rule we should ensure the initial `chainId`/`networkType` is set via the actual network controller state, passed in via the constructor.

### PR DESCRIPTION
**Pull request by kanthesha**
## Explanation

The network configuration gets updated whenever the network state changes, but until the first state change it might be invalid. So we need to initialise with the selected network from NetworkController.
- Initial network set with selectedNetworkClientId from `getState` of `NetworkController`
- Provider removed from constructor, as we can get the provider from selectedNetworkClient

## References

* Fixes #843 

### `@metamask/ens-controller`

- **BREAKING**: Provider removed from constructor, instead depends on selectedNetworkClient for provider
- **FIXED**: Initial network set with selectedNetworkClientId from `getState` of `NetworkController`.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

File: packages/ens-controller/src/EnsController.ts [hunk 1]
```diff
@@ -295,6 +277,38 @@ export class EnsController extends BaseController<
...
+      this.#ethProvider = new Web3Provider(selectedNetworkClient.provider, {
+        chainId: convertHexToDecimal(currentChainId),
+        name: CHAIN_ID_TO_ETHERS_NETWORK_NAME_MAP[currentChainId as ChainId],
+        ensAddress: registriesByChainId[parseInt(currentChainId, 16)],
+      });
+    } else {
+      this.#ethProvider = null;
+    }
+  }
+
```
Comment (mikesposito) [inline packages/ens-controller/src/EnsController.ts:311]: Do you think that using [`NetworkController:getSelectedNetworkClient`](https://github.com/MetaMask/core/blob/8ffcb839b1f3183316bcbbe26375a1c7bd7458d8/packages/network-controller/src/NetworkController.ts#L301) would simplify the logic here letting NetworkController do the hard work, or is it unusable here for some reason?

Comment (mikesposito) [reply packages/ens-controller/src/EnsController.ts:311]: This comment probably applies also to the `constructor` logic

Comment (mikesposito) [reply packages/ens-controller/src/EnsController.ts]: Ah sorry, I see, we also need the `clientId` which is not provided by `:getSelectedNetworkClient`. 
Though, do we need to create a new instance of `Web3Provider`? is there a reason why we can't use what's provided by `NetworkController` in this case? 

I see that in the current extension implementation the `provider` passed to `EnsController` comes directly from `NetworkController`: https://github.com/MetaMask/metamask-extension/blob/cd30d782a3097a00983601ab3211261d8b63b207/app/scripts/metamask-controller.js#L530

**Review by mikesposito — APPROVED** [review]
Looks good!
