### PR TITLE
chore(lint): Fix suppressed ESLint errors in `sample-controllers` package

### LINKED ISSUE #7389: Fix suppressed lint errors in `sample-controllers`
Fix suppressed lint errors in this package.

### PR DESCRIPTION
**Pull request by Mrtenz**
## Explanation

This fixes all suppressed ESLint errors in the `sample-controllers` package.

## References

Closes #7389.

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've communicated my changes to consumers by [updating changelogs for packages I've changed](https://github.com/MetaMask/core/tree/main/docs/contributing.md#updating-changelogs)
- [ ] I've introduced [breaking changes](https://github.com/MetaMask/core/tree/main/docs/breaking-changes.md) in this PR and have prepared draft pull requests for clients and consumer packages to resolve them

---

> [!NOTE]
> Adds explicit return types and error capture in sample controllers/services, updates tests accordingly, and removes related ESLint suppressions.
> 
> - **Controllers**:
>   - `SampleGasPricesController`
>     - Add explicit return types to `updateGasPrices` and `#onSelectedNetworkClientIdChange`.
>     - On network client change, call `updateGasPrices(...).catch(...)` and forward errors to `messenger.captureException`.
>   - `SamplePetnamesController`
>     - Add explicit `void` return type to `assignPetname`.
> - **Service**:
>   - `SampleGasPricesService`
>     - Add explicit `IDisposable` return types for `onRetry`, `onBreak`, `onDegraded`.
> - **Tests**:
>   - `sample-gas-prices-controller.test.ts`: mock `captureException`; add test asserting it’s called on fetch failure.
>   - `sample-gas-prices-service.test.ts`: make `onRetry` callbacks non-async and handle `clock.nextAsync()` via `.catch(console.error)`.
> - **Lint**:
>   - Remove ESLint suppressions for `sample-controllers` files in `eslint-suppressions.json`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 82ce74518de24420cf053f86d7ad0d09c2e0e356. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/sample-controllers/src/sample-gas-prices-controller.ts [hunk 1]
```diff
@@ -109,6 +110,7 @@ export type SampleGasPricesControllerActions =
  * Actions from other messengers that {@link SampleGasPricesMessenger} calls.
  */
 type AllowedActions =
+  | ErrorReportingServiceCaptureExceptionAction
```
Comment (Gudahtt) [inline packages/sample-controllers/src/sample-gas-prices-controller.ts]: We'd have to document this as a breaking change. I know these are meant to be examples, but they're published and actually used in the clients as part of an example UI feature as well.

Though.... there is an alternative that is both preferable and non-breaking, and that is to use `messenger.captureException` (see https://github.com/MetaMask/core/blob/206599b079eb0a20b5162e4cf11a065384245973/packages/messenger/src/Messenger.ts#L263)
This was added essentially to replace the error reporting service, and it does the same thing

File: packages/sample-controllers/src/sample-gas-prices-controller.ts [hunk 2]
```diff
@@ -293,9 +295,9 @@ export class SampleGasPricesController extends BaseController<
    *
    * @param selectedNetworkClientId - The globally selected network client ID.
    */
-  async #onSelectedNetworkClientIdChange(
```
Comment (Gudahtt) [inline packages/sample-controllers/src/sample-gas-prices-controller.ts:296]: Not sure how I feel about this "no misused promises" rule. There wasn't really any misused promise here, it was intentional for this to be async.

I guess it's theoretically possible that a function that is expected to return `void` would break something if it returned a value, like a Promise. I see the value of aligning on the type. Hmm.

Maybe we can consider updating the messenger to allow `Promise<void>` for subscribers as well. That wouldn't solve this for 3rd party libraries though.

Comment (Gudahtt) [reply packages/sample-controllers/src/sample-gas-prices-controller.ts:296]: Tempted to suggest that we disable the `checksVoidReturn` option: https://typescript-eslint.io/rules/no-misused-promises/

Comment (Mrtenz) [reply packages/sample-controllers/src/sample-gas-prices-controller.ts:296]: My main concern is unhandled promise rejections if the caller doesn't handle them, which won't be the case if the caller expects a void return. Not sure about disabling `checksVoidReturn`.

File: packages/sample-controllers/src/sample-gas-prices-controller.ts (hunk 1 above)
Comment (Mrtenz) [reply packages/sample-controllers/src/sample-gas-prices-controller.ts]: I wasn't aware it was intended to replace the error reporting service. Wondering if we should deprecate that then, to make it clear?

Comment (Mrtenz) [reply packages/sample-controllers/src/sample-gas-prices-controller.ts]: Updated in this commit: 82ce74518de24420cf053f86d7ad0d09c2e0e356.

File: packages/sample-controllers/src/sample-gas-prices-controller.ts (hunk 2 above)
Comment (Gudahtt) [reply packages/sample-controllers/src/sample-gas-prices-controller.ts:296]: Yeah, fair. Especially problematic for mobile, where it would crash the app.

File: packages/sample-controllers/src/sample-gas-prices-controller.ts (hunk 1 above)
Comment (Gudahtt) [reply packages/sample-controllers/src/sample-gas-prices-controller.ts]: Definitely overdue to deprecate that package

Comment (Mrtenz) [reply packages/sample-controllers/src/sample-gas-prices-controller.ts]: Will take care of that tomorrow!

File: packages/sample-controllers/src/sample-gas-prices-controller.test.ts [hunk 3]
```diff
@@ -201,6 +201,52 @@ describe('SampleGasPricesController', () => {
...
+
+        const fetchGasPrices = jest.fn(async (givenChainId) => {
+          if (givenChainId === chainId) {
+            throw new Error('Failed to fetch gas prices');
+          }
+
+          throw new Error(`Unrecognized chain ID '${givenChainId}'`);
+        });
+
+        const captureException = jest.spyOn(rootMessenger, 'captureException');
```
[the remark this answers is not in the document]
Comment (Mrtenz) [reply packages/sample-controllers/src/sample-gas-prices-controller.test.ts:217]: This works as expected.
